# Generated by Django 5.0.1 on 2024-01-16 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=100, verbose_name='Titulo')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('idusuario', models.IntegerField(db_column='idUsuario', primary_key=True, serialize=False)),
                ('nombresapellidosusuarios', models.CharField(db_column='nombresApellidosUsuarios', max_length=70)),
                ('emailusuario', models.CharField(db_column='emailUsuario', max_length=45)),
                ('contrasenausuario', models.CharField(db_column='contrasenaUsuario', max_length=45)),
            ],
        ),
    ]
