# Generated by Django 5.0.1 on 2024-01-16 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parce_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={'managed': False},
        ),
    ]
