# Generated by Django 5.0.1 on 2024-01-18 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parce_app', '0004_dispositivo_rol_usuariorol'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Dispositivo',
        ),
    ]
