# Generated by Django 5.0.1 on 2024-01-18 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parce_app', '0005_delete_dispositivo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dispositivo',
            fields=[
                ('iddispositivo', models.AutoField(db_column='idDispositivo', primary_key=True, serialize=False)),
                ('nombredispositivo', models.CharField(db_column='nombreDispositivo', max_length=45)),
                ('referenciadispositivo', models.CharField(db_column='referenciaDispositivo', max_length=45)),
                ('estado_dispositivo', models.BooleanField(db_column='estado_dispositivo', default=True)),
            ],
            options={
                'db_table': 'dispositivo',
                'managed': False,
            },
        ),
    ]
