# Generated by Django 5.0.1 on 2024-01-18 22:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parce_app', '0006_dispositivo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Metricas',
            fields=[
                ('idmetricas', models.AutoField(db_column='idMetricas', primary_key=True, serialize=False)),
                ('nombremetrica', models.CharField(db_column='nombreMetrica', max_length=45)),
            ],
            options={
                'db_table': 'metricas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UsuariosDispositivo',
            fields=[
                ('idusuarios_dispositivo', models.AutoField(db_column='idUsuarios-dispositivo', primary_key=True, serialize=False)),
                ('nombreusuariodispositivo', models.CharField(db_column='nombreUsuarioDispositivo', max_length=45)),
                ('estado_dispositivo', models.BooleanField(db_column='estado_dispositivo', default=True)),
            ],
            options={
                'db_table': 'usuarios-dispositivo',
                'managed': False,
            },
        ),
        migrations.AlterModelTable(
            name='usuariorol',
            table='usuario-rol',
        ),
        migrations.CreateModel(
            name='MetricasDispositivo',
            fields=[
                ('usuarios_dispositivo_idusuarios_dispositivo', models.OneToOneField(db_column='Usuarios-dispositivo_idUsuarios-dispositivo', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='parce_app.usuariosdispositivo')),
            ],
            options={
                'db_table': 'metricas-dispositivo',
                'managed': False,
            },
        ),
    ]
